services:
  db:
   image: postgres
   restart: always
   shm_size: 128mb
   environment:
     POSTGRES_PASSWORD: 123456abc
     POSTGRES_USER: cody
     POSTGRES_DB: musicAPIdb
   healthcheck:
    test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
    interval: 30s
    timeout: 60s
    retries: 5
    start_period: 80s
   volumes:
     - ./sql:/docker-entrypoint-initdb.d
    #  - ./dbdata:/var/lib/postgresql/data
   ports:
     - 5432:5432
   # command: ["postgres", "-c", "log_statement=all"] # Enables verbose logging

    
  api:  
    build: 
      context: ./MusicAPI
    restart: always
    environment:
      - ConnectionStrings__PostgresConnection=Host=db;Database=musicAPIdb;Username=cody;Password=123456abc;
    depends_on:
      - db
    ports:
      - 4110:8080